export interface Service {
    id: string;
    slug: string;
    name: string;
    nameEn: string;
    tagline: string;
    description: string;
    category: string;
    target: string;
    targetAge: string[];
    features: string[];
    pros: string[];
    cons: string[];
    recommended: string[];
    affiliateUrl: string;
    ctaText: string;
    color: string;
}

export const services: Service[] = [
    {
        id: 'rokkaku',
        slug: 'rokkaku-brain-pillow',
        name: '六角脳枕',
        nameEn: 'ROKKAKU BRAIN PILLOW',
        tagline: 'ナイツも絶賛！ヒンヤリ冷感で快適安眠',
        description: '独自の六角形カット構造と冷感素材を組み合わせた安眠枕。頭を心地よくクールダウンし、寝返りを打ちやすい設計で朝まで快適。テレビでも多数紹介された話題の枕。',
        category: '冷感安眠枕',
        target: '暑がりで寝苦しい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            '独自の六角形カット構造',
            'ヒンヤリ冷感素材で快適',
            '寝返りが打ちやすい設計',
            'テレビ・メディアで多数紹介',
        ],
        pros: [
            '冷感素材で頭がひんやり快適',
            '寝返りがスムーズにできる',
            'メディア紹介多数で信頼性が高い',
            '独自構造で肩こり軽減',
        ],
        cons: [
            '冬場は冷たすぎると感じることも',
            '独自形状に慣れが必要',
            '価格がやや高め',
        ],
        recommended: [
            '頭が暑くて寝苦しい人',
            '寝返りが多くて目が覚めてしまう人',
            'テレビで見て気になっていた人',
            '今の枕で肩こりが改善しない人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=3N202O+3QK6FU+2DDC+5ZEMQ',
        ctaText: '詳細を見る',
        color: '#0ea5e9',
    },
    {
        id: 'kenmin',
        slug: 'kenmin-pillow',
        name: '健眠枕',
        nameEn: 'KENMIN PILLOW',
        tagline: '寝返りのしやすさと寝姿勢を追求',
        description: '「寝返りのしやすさ」と「正しい寝姿勢」を両立した、ワンランク上の安眠枕。人間工学に基づく設計で自然な枕の高さを維持し、質の高い睡眠をサポートします。',
        category: '寝姿勢サポート枕',
        target: '寝姿勢を改善したい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            '人間工学に基づく寝姿勢設計',
            'スムーズな寝返りをサポート',
            '自然な首のカーブを維持',
            'ワンランク上の寝心地',
        ],
        pros: [
            '寝返りが楽にできる',
            '正しい寝姿勢をキープできる',
            '朝起きた時の体の痛みが軽減',
            'どの寝姿勢でもフィット',
        ],
        cons: [
            '好みの硬さに合わないことも',
            '慣れるまで数日かかる場合がある',
            '他のブランドに比べ知名度が低い',
        ],
        recommended: [
            '寝返りで目が覚めてしまう人',
            '朝起きると体が痛い人',
            '正しい寝姿勢で寝たい人',
            '今の枕では寝心地がイマイチな人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D3JIU2+2DDC+AF3ATU',
        ctaText: '詳細を見る',
        color: '#10b981',
    },
    {
        id: 'curere',
        slug: 'curere-the-makura',
        name: 'Cure:Re THE MAKURA',
        nameEn: 'CURE:RE THE MAKURA',
        tagline: '特許取得の整体枕。プロが認めた本格派',
        description: '整体師が開発した特許取得の整体枕。独自の構造が首と頭を的確にサポートし、整体に通うような感覚で毎晩のケアを実現。整体のプロからも高い支持を得ている本格派枕。',
        category: '整体枕',
        target: '首・肩の根本的な改善をしたい人',
        targetAge: ['30代', '40代', '50代'],
        features: [
            '特許取得の整体構造',
            '整体師が開発・監修',
            '首と頭を最適ポジションにサポート',
            '毎晩が整体のようなケアタイム',
        ],
        pros: [
            '整体に通う頻度を減らせる',
            '首・肩の悩みに根本からアプローチ',
            '特許技術で他にない構造',
            'プロの整体師からも支持',
        ],
        cons: [
            '価格が3万円台とやや高い',
            '整体的アプローチに抵抗がある人には不向き',
            '柔らかい枕が好きな人には硬く感じる',
        ],
        recommended: [
            '整体に定期的に通っている人',
            '首・肩の痛みを根本から改善したい人',
            'プロが認めた枕が欲しい人',
            '高くても本当に効果のある枕が欲しい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=3HIII2+AYQLSQ+4GZK+5Z6WY',
        ctaText: '詳細を見る',
        color: '#ef4444',
    },
    {
        id: 'survaq',
        slug: 'survaq-hot-pillow',
        name: '首と肩がホっとする枕PLUS',
        nameEn: 'SURVAQ HOT PILLOW PLUS',
        tagline: '温めて癒す。首と肩のための温熱枕',
        description: '首と肩を温める温熱機能付き枕。じんわりとした温かさが筋肉のこわばりをほぐし、血行を促進。冷え性の方にも最適な、温めて癒すコンセプトの新しい枕です。',
        category: '温熱枕',
        target: '冷え性・温めケアをしたい人',
        targetAge: ['30代', '40代', '50代'],
        features: [
            '温熱機能で首と肩を温める',
            '血行促進で筋肉をほぐす',
            '冷え性対策にも効果的',
            '温めて癒すコンセプト',
        ],
        pros: [
            '温かさで首・肩がリラックス',
            '冷え性の方に特に好評',
            '温熱で血行促進効果が期待できる',
            '寝ながらケアできる手軽さ',
        ],
        cons: [
            '夏場は暑く感じることがある',
            '温熱機能に頼りすぎる面がある',
            '洗濯に注意が必要',
        ],
        recommended: [
            '冷え性で首・肩が冷える人',
            '温めると楽になるタイプの肩こりの人',
            '寝ながらケアしたい人',
            '冬場の寝つきが悪い人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D744GQ+573A+60OXE',
        ctaText: '詳細を見る',
        color: '#f97316',
    },
    {
        id: 'gokumin',
        slug: 'gokumin-pillow',
        name: 'GOKUMIN',
        nameEn: 'GOKUMIN',
        tagline: '受賞実績多数！コスパ最強の実力派',
        description: '数々のアワードを受賞した実力派ブランド。高品質なのにお手頃価格で、マットレスと枕であなたの睡眠の悩みを解決します。コスパを重視する方に最適な選択肢。',
        category: 'コスパ実力派枕',
        target: 'コスパ重視で良質な枕が欲しい人',
        targetAge: ['20代', '30代', '40代'],
        features: [
            '多数のアワード受賞実績',
            '高品質なのにお手頃価格',
            '豊富なラインナップ',
            '睡眠の悩みをトータルサポート',
        ],
        pros: [
            'コスパが非常に良い',
            '受賞実績が品質の証明',
            '初めての枕選びにも最適',
            '種類が豊富で選びやすい',
        ],
        cons: [
            '高級枕ほどの特殊機能はない',
            '実店舗での取り扱いが少ない',
            'ブランドの知名度が発展途上',
        ],
        recommended: [
            '予算は抑えたいけど品質は妥協したくない人',
            '初めて「ちゃんとした枕」を買う人',
            '受賞実績のある枕を選びたい人',
            'まずはお手頃に試してみたい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+CY6ME2+539S+5YJRM',
        ctaText: '詳細を見る',
        color: '#6366f1',
    },
    {
        id: 'mymakura',
        slug: 'my-makura',
        name: 'マイまくら（オーダーメイド枕）',
        nameEn: 'MY MAKURA',
        tagline: '世界にひとつ、あなただけのオーダーメイド枕',
        description: '寝具専門店が作る特許取得のオーダーメイド枕。あなたの頭の形・首の高さ・寝姿勢を計測し、完全オーダーメイドで作成。一般医療機器のリカバリーウェアも取り扱い、トータルで睡眠をサポート。',
        category: 'オーダーメイド枕',
        target: '自分だけの枕をオーダーしたい人',
        targetAge: ['30代', '40代', '50代'],
        features: [
            '特許取得のオーダーメイド製法',
            '頭の形・首の高さを計測して製作',
            '一般医療機器リカバリーウェアも展開',
            '寝具専門店ならではの品質',
        ],
        pros: [
            '自分だけにぴったりの枕が手に入る',
            '既製品で合わなかった人の最終手段',
            '寝具専門店の確かな品質',
            'メンテナンス対応あり',
        ],
        cons: [
            '価格が高め',
            '計測のために来店が必要な場合がある',
            '完成までに時間がかかることがある',
        ],
        recommended: [
            '既製品の枕が合わなかった人',
            '自分だけの完璧な枕が欲しい人',
            '枕の高さや硬さに細かいこだわりがある人',
            '長く使える一生ものの枕が欲しい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D9HUVU+3KHK+BWVTE',
        ctaText: '詳細を見る',
        color: '#8b5cf6',
    },
    {
        id: 'yokone3b',
        slug: 'yokone3b',
        name: 'YOKONE3B',
        nameEn: 'YOKONE3B',
        tagline: '横向き寝専用設計。美容と睡眠の両立',
        description: '横向き寝に特化した専用設計枕。横向きで寝ても顔にシワができにくく、肌荒れもサポート。いびき対策にも効果的で、美容と健康を両立したい方に最適です。',
        category: '横向き寝専用枕',
        target: '横向きで寝ることが多い人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            '横向き寝に特化した専用設計',
            '顔のシワや肌荒れをサポート',
            'いびき対策にも効果的',
            '美容と睡眠の両立',
        ],
        pros: [
            '横向き寝で最高のフィット感',
            '顔の圧迫が少なくシワ対策に',
            'いびきの軽減が期待できる',
            '美容を気にする方にも安心',
        ],
        cons: [
            '仰向け寝には向かない',
            '横向き寝専用なので用途が限られる',
            'サイズが大きめ',
        ],
        recommended: [
            '横向きで寝ることが多い人',
            '寝ジワや肌荒れが気になる人',
            'いびきを改善したい人',
            '美容も意識した枕選びがしたい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D0KCT6+2HEW+64AT9E',
        ctaText: '詳細を見る',
        color: '#ec4899',
    },
    {
        id: 'recovery-sleep',
        slug: 'recovery-sleep',
        name: 'Recovery Sleep',
        nameEn: 'RECOVERY SLEEP',
        tagline: '温熱効果で睡眠をアップデート',
        description: '温熱効果のある特殊素材を使い、寝ている間に体をリカバリー。遠赤外線効果で体を芯から温め、翌朝のスッキリ感が違います。疲労回復と質の高い睡眠を両立。',
        category: 'リカバリー寝具',
        target: '疲労回復と睡眠の質を上げたい人',
        targetAge: ['30代', '40代', '50代'],
        features: [
            '温熱効果で体をリカバリー',
            '遠赤外線素材を使用',
            '寝ている間に疲労回復',
            '翌朝のスッキリ感が向上',
        ],
        pros: [
            '寝るだけで疲労回復効果',
            '遠赤外線で体を芯から温める',
            '翌朝の目覚めが違う',
            '冷え性の改善も期待できる',
        ],
        cons: [
            '夏場は暑く感じることがある',
            '即効性は感じにくいことも',
            '価格がやや高め',
        ],
        recommended: [
            '毎日の疲れが取れにくい人',
            '冷え性で寝つきが悪い人',
            '朝スッキリ起きたい人',
            '寝ながら体のケアをしたい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D1R80Q+53VQ+5YJRM',
        ctaText: '詳細を見る',
        color: '#f59e0b',
    },
    {
        id: 'oyasumi-shop',
        slug: 'oyasumi-shop',
        name: '枕と眠りのおやすみショップ！',
        nameEn: 'OYASUMI SHOP',
        tagline: '枕専門店だから見つかる、あなただけの一品',
        description: '枕・抱き枕・足枕など「枕」に特化した専門ショップ。豊富な品揃えの中から、素材・高さ・硬さ・用途別に最適な枕を探せます。専門店ならではの知識とラインナップで、あなたにぴったりの一品が見つかります。',
        category: '枕専門店',
        target: 'いろいろな枕を比較して選びたい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            '枕に特化した専門店の豊富な品揃え',
            '素材・高さ・硬さ別に選べる',
            '抱き枕・足枕など用途別枕も充実',
            '専門店ならではの詳しい商品説明',
        ],
        pros: [
            '1つのショップで多種多様な枕を比較できる',
            '専門店だからこその詳しい枕選びガイド',
            '用途別（横向き用・いびき対策用等）に探せる',
            '予算に合わせた幅広い価格帯',
        ],
        cons: [
            '選択肢が多く迷う可能性がある',
            '実店舗がないのでオンラインのみ',
            '一部商品は在庫切れの場合がある',
        ],
        recommended: [
            'いろいろな枕を見比べてから決めたい人',
            '特殊な用途の枕（抱き枕・足枕等）を探している人',
            '予算に合わせて幅広い選択肢から選びたい人',
            '枕選びに詳しいアドバイスが欲しい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+CZYX7E+5LHW+5YJRM',
        ctaText: '詳細を見る',
        color: '#14b8a6',
    },
    {
        id: 'brain-sleep-snoreless',
        slug: 'brain-sleep-snoreless',
        name: 'ブレインスリープ ピロー スノーレス',
        nameEn: 'BRAIN SLEEP PILLOW SNORELESS',
        tagline: '横向き寝を促進し、快適な眠りを',
        description: '脳と睡眠の科学から生まれたブレインスリープのいびき対策枕。独自の構造が自然に横向き寝を促し、いびきの原因となる気道の狭まりを軽減。通気性にも優れ、快適な睡眠環境を実現します。',
        category: 'いびき対策枕',
        target: 'いびきに悩む人・横向き寝で快適に寝たい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            '脳と睡眠の科学から開発',
            '自然に横向き寝を促進する構造',
            'いびき対策に特化した設計',
            '優れた通気性で蒸れにくい',
        ],
        pros: [
            'いびき軽減が期待できる',
            '横向き寝が自然にできる構造',
            '通気性が高く蒸れにくい',
            '科学的アプローチで信頼性が高い',
        ],
        cons: [
            '価格がやや高め',
            '仰向け寝がメインの人には不向き',
            '効果に個人差がある',
        ],
        recommended: [
            'いびきを改善したい人',
            'パートナーにいびきを指摘される人',
            '横向き寝で快適に寝たい人',
            '科学的根拠のある枕が欲しい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+DAOQ3E+4KU6+1NJK7M',
        ctaText: '詳細を見る',
        color: '#3b82f6',
    },
    {
        id: 'brain-sleep-aio',
        slug: 'brain-sleep-all-in-one',
        name: 'ブレインスリープ ALL IN ONE',
        nameEn: 'BRAIN SLEEP ALL IN ONE',
        tagline: '枕・マットレス・掛布団が一体化した革新的スリープギア',
        description: '枕・マットレス・掛布団がひとつにまとまった革新的なオールインワンスリープギア。これ1つで寝具一式が揃い、持ち運びも簡単。ミニマリストや引っ越しが多い方にも最適。',
        category: 'オールインワン寝具',
        target: '寝具を一式まとめて揃えたい人',
        targetAge: ['20代', '30代', '40代'],
        features: [
            '枕・マットレス・掛布団が一体化',
            'これ1つで寝具一式が揃う',
            '持ち運びしやすいコンパクト設計',
            'ブレインスリープの睡眠科学を凝縮',
        ],
        pros: [
            '寝具を個別に揃える必要なし',
            '引っ越しや出張にも便利',
            'ブレインスリープブランドの安心感',
            'スペースを取らないコンパクト設計',
        ],
        cons: [
            '個別に寝具を選びたい人には不向き',
            '価格がやや高め',
            'カスタマイズ性は低い',
        ],
        recommended: [
            '寝具を一式まとめて買い替えたい人',
            'ミニマリストや省スペース派',
            '引っ越しや出張が多い人',
            '手軽に良質な睡眠環境を整えたい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D4QE1M+4KU6+15OK2A',
        ctaText: '詳細を見る',
        color: '#1e40af',
    },
    {
        id: 'brain-sleep-neck',
        slug: 'brain-sleep-neck-conditioning',
        name: 'ブレインスリープ ピロー ネックコンディショニング',
        nameEn: 'BRAIN SLEEP PILLOW NECK CONDITIONING',
        tagline: '寝ながら身体を整えるコンディショニング枕',
        description: '寝ている間に首と身体を整えるコンディショニング枕。ブレインスリープの睡眠科学と身体のメカニズムを融合し、朝起きた時の首・肩の違和感を軽減。毎晩のケアが翌朝のコンディションを変える。',
        category: 'コンディショニング枕',
        target: '首・肩のコンディションを整えたい人',
        targetAge: ['30代', '40代', '50代'],
        features: [
            '寝ながら首と身体をコンディショニング',
            'ブレインスリープの睡眠科学',
            '朝の首・肩の違和感を軽減',
            '毎晩のケアで体調を整える',
        ],
        pros: [
            '寝るだけで首のコンディショニング',
            '科学的アプローチで信頼性が高い',
            '朝のスッキリ感が向上',
            '毎晩の継続ケアが可能',
        ],
        cons: [
            '価格が高め',
            '効果実感に個人差がある',
            '慣れるまで時間がかかることも',
        ],
        recommended: [
            '朝起きると首が痛い人',
            'デスクワークで首が凝りやすい人',
            '寝ながら体を整えたい人',
            '科学的根拠のある枕が欲しい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D5BTNE+4KU6+TS3OI',
        ctaText: '詳細を見る',
        color: '#059669',
    },
    {
        id: 'brain-sleep-store',
        slug: 'brain-sleep-store',
        name: 'BRAIN SLEEP STORE',
        nameEn: 'BRAIN SLEEP STORE',
        tagline: '最高の睡眠を届けるセレクトショップ',
        description: 'ブレインスリープの全商品が揃う公式セレクトショップ。枕・マットレス・ウェアなど、最高の睡眠のためのアイテムを幅広くラインナップ。自分に合った睡眠アイテムを見つけたい方に。',
        category: '睡眠セレクトショップ',
        target: 'ブレインスリープの商品を色々見たい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            'ブレインスリープ全商品が揃う公式ショップ',
            '枕からウェアまで幅広いラインナップ',
            '最高の睡眠のための総合セレクト',
            '限定商品や最新アイテムも入手可能',
        ],
        pros: [
            'ブレインスリープの全商品を比較できる',
            '枕以外の睡眠アイテムも充実',
            '公式ショップの安心感',
            '最新商品をいち早くチェックできる',
        ],
        cons: [
            'ブレインスリープ以外の商品はない',
            '選択肢が多く迷うことも',
            '価格帯がやや高め',
        ],
        recommended: [
            'ブレインスリープブランドに興味がある人',
            '睡眠アイテムを総合的に揃えたい人',
            '色々比較して自分に合うものを選びたい人',
            '公式ショップで安心して買いたい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D5X996+4KU6+HV7V6',
        ctaText: '詳細を見る',
        color: '#7c3aed',
    },
    {
        id: 'brain-sleep-standard',
        slug: 'brain-sleep-standard',
        name: 'ブレインスリープ ピロー（スタンダード）',
        nameEn: 'BRAIN SLEEP PILLOW STANDARD',
        tagline: '最高の睡眠枕。脳と睡眠の科学から生まれた',
        description: 'ブレインスリープのフラッグシップ枕。脳と睡眠の科学に基づき開発された、超通気性と最適な頭部サポートを実現する枕。抜群の通気性で深部体温を下げ、深い眠りをサポートします。',
        category: '高機能枕',
        target: '最高品質の枕で睡眠を変えたい人',
        targetAge: ['20代', '30代', '40代', '50代'],
        features: [
            '脳と睡眠の科学から開発されたフラッグシップ',
            '超通気性で深部体温を下げる',
            '頭にフィットする最適サポート',
            'シャワーで丸洗い可能で清潔',
        ],
        pros: [
            '圧倒的な通気性で頭がムレない',
            '科学的根拠に基づいた設計',
            '丸洗いできてずっと清潔',
            '深い眠りをサポート',
        ],
        cons: [
            '価格が3万円台と高め',
            '柔らかめの寝心地が合わない人も',
            '独自素材に慣れが必要',
        ],
        recommended: [
            '頭の蒸れが気になる人',
            '最高品質の枕を求める人',
            '清潔さを重視する人',
            '睡眠の質を本気で改善したい人',
        ],
        affiliateUrl: 'https://px.a8.net/svt/ejp?a8mat=4AZGC6+D6IOUY+4KU6+5YRHE',
        ctaText: '詳細を見る',
        color: '#0891b2',
    },
];

export function getServiceBySlug(slug: string): Service | undefined {
    return services.find((s) => s.slug === slug);
}
